# Generated by ./configure on 2026-08-18T00:13:37Z
# Re-run ./configure to change.

PREFIX  := /usr/local
BINDIR  := /usr/local/bin
DATADIR := /usr/local/share

CC      := gcc
MAKE    := gmake

OS_UNAME := Linux
OS_ID    := pop

# Legible C11 flags (matching hush-c expectations)
CFLAGS  := -std=c11 -Wall -Wextra -Werror -Wconversion -Wshadow -Iinclude -O2
