# Generated by ./configure on 2026-08-17T22:27:28Z
# Do not edit by hand. Re-run ./configure to change.

PREFIX  := /usr/local
BINDIR  := /usr/local/bin
DATADIR := /usr/local/share/hush

CC      := gcc
MAKE    := gmake

OS_UNAME := Linux
OS_ID    := pop

# CFLAGS for legible C11 (hush-c)
CFLAGS  := -std=c11 -Wall -Wextra -Werror -Wconversion -Wshadow -Iinclude -O2
