# Top-level Makefile for Hush C (Linux + *BSD)
# Workflow:
#   ./configure [PREFIX=...]
#   make
#   make test
#   make install [PREFIX=...]     # installs hush-relay + .desktop + icons
#   make uninstall                # removes PREFIX artifacts install owns (keeps build tree)
#   make clean                    # uninstalls PREFIX artifacts, then scrubs the
#                                 # build tree (objects, libs, in-tree binary,
#                                 # tarballs), so the next
#                                 # ./configure ; make ; make install starts
#                                 # from a clean install. Never touches
#                                 # ~/.hush/ runtime data.
#   make deb                      # Build DEB package (requires debhelper)
#   make rpm                      # Build RPM package (requires rpmbuild)
#   make flatpak                  # Build Flatpak package (requires flatpak-builder)
#   make openbsd                  # Stage OpenBSD destroot; pkg_create on OpenBSD
#   make freebsd                  # Stage FreeBSD destroot; pkg create on FreeBSD
#   make bsd                      # openbsd + freebsd
#   make dist                     # Create source tarball

# config.mk is generated by ./configure; the ?= defaults below let
# `make clean` / `make uninstall` run safely even when it is absent
# (virgin checkout), resolving to the same PREFIX=~/.local default.
-include config.mk

PREFIX ?= $(HOME)/.local
BINDIR ?= $(PREFIX)/bin
DATADIR ?= $(PREFIX)/share
# Isolated-eval honesty: `make install PREFIX=/tmp/x` re-derives BINDIR and
# DATADIR from PREFIX unless they were also given on the command line.
# Otherwise a stale config.mk baked by an earlier ./configure (e.g. ~/.local)
# would scatter files outside the requested PREFIX. Values from the
# environment or command line (origin != file) are always honored.
ifeq ($(origin PREFIX),command line)
ifeq ($(origin BINDIR),file)
BINDIR := $(PREFIX)/bin
endif
ifeq ($(origin DATADIR),file)
DATADIR := $(PREFIX)/share
endif
endif
# Rebuild guard port: $HUSH_PORT, else 10555 (HUSH_DEFAULT_PORT).
# Override per-invocation, e.g. `HUSH_PORT=10556 make`.
GUARD_PORT ?= $(HUSH_PORT)

.PHONY: all test clean install uninstall guard check-prefix check-stamp package-deb package-rpm packages deb rpm flatpak openbsd freebsd bsd dist
# guard: is defined below but must never become the default goal.
.DEFAULT_GOAL := all

# Fail-loud when a live relay owns the guard port: never build or install
# over a running hive. Stop it first (`hush-relay --quit <port>`); `make
# clean` (kill-relay.sh) is the only path that kills.
# Port-scoped: only the guard port is checked ($HUSH_PORT, else 10555); a
# relay on another port does not block the build unless HUSH_PORT matches.
guard:
	@sh scripts/check-relay-port.sh $(GUARD_PORT)

# An empty PREFIX would resolve BINDIR to /bin and let install/uninstall
# scribble outside any prefix; an empty BINDIR would resolve install targets
# to /hush-relay (root). configure refuses to generate an empty PREFIX; this
# catches `make install PREFIX=` / `make install BINDIR=` style overrides
# instead. DATADIR is guarded for the same reason (empty DATADIR would drop
# desktop entries and icons at /applications and /icons).
check-prefix:
	@if [ -z "$(PREFIX)" ]; then \
		echo "error: empty PREFIX. Pass a real prefix, e.g. make install PREFIX=/tmp/hush-eval,"; \
		echo "or unset PREFIX to use the configured default (\$$HOME/.local)."; \
		exit 1; \
	fi; \
	if [ -z "$(BINDIR)" ]; then \
		echo "error: empty BINDIR. Pass a real bindir, e.g. make install BINDIR=/tmp/hush-eval/bin,"; \
		echo "or unset BINDIR to derive it from PREFIX."; \
		exit 1; \
	fi; \
	if [ -z "$(DATADIR)" ]; then \
		echo "error: empty DATADIR. Pass a real datadir, e.g. make install DATADIR=/tmp/hush-eval/share,"; \
		echo "or unset DATADIR to derive it from PREFIX."; \
		exit 1; \
	fi

# Stale-stamp tripwire (warn-only): config.mk bakes HUSH_BUILD_SHA at
# configure time, so committing after configure leaves the binary stamped
# with the old SHA. tests/check_build.sh still fails the suite on mismatch;
# this just warns early during make/install without breaking tarball builds
# (no git) or unconfigured trees (no config.mk, empty HUSH_BUILD_SHA).
check-stamp:
	@baked="$(HUSH_BUILD_SHA)"; \
	head=""; \
	if command -v git >/dev/null 2>&1; then \
		head=$$(git rev-parse --short HEAD 2>/dev/null || true); \
	fi; \
	if [ -n "$$baked" ] && [ "$$baked" != "unknown" ] \
		&& [ -n "$$head" ] && [ "$$baked" != "$$head" ]; then \
		echo "warning: baked build SHA ($$baked) != HEAD short ($$head); re-run ./configure."; \
	fi

all: guard check-stamp
	$(MAKE) -C hush-c all CC="$(CC)" CFLAGS="$(CFLAGS)" LDFLAGS="$(LDFLAGS)"

test:
	$(MAKE) -C hush-c test CC="$(CC)" CFLAGS="$(CFLAGS)" LDFLAGS="$(LDFLAGS)"

clean: check-prefix
	@sh scripts/kill-relay.sh
	$(MAKE) -C hush-c clean
	$(MAKE) uninstall
	rm -f *.tar.gz

install: guard check-prefix check-stamp
	$(MAKE) -C hush-c install \
		DESTDIR="$(DESTDIR)" \
		PREFIX="$(PREFIX)" \
		BINDIR="$(BINDIR)" \
		DATADIR="$(DATADIR)" \
		ENABLE_STUN_TURN="$(ENABLE_STUN_TURN)"
	@echo
	@echo "To refresh your application launcher (Linux):"
	@echo "  update-desktop-database $(DATADIR)/applications || true"
	@echo "  gtk-update-icon-cache -f $(DATADIR)/icons/hicolor || true"
	@echo
	@echo "hush-relay should now appear in your menu / launcher."

uninstall: check-prefix
	$(MAKE) -C hush-c uninstall \
		DESTDIR="$(DESTDIR)" \
		PREFIX="$(PREFIX)" \
		BINDIR="$(BINDIR)" \
		DATADIR="$(DATADIR)"

# --- DEB packaging ---
deb:
	dpkg-buildpackage -us -uc -b
	@echo
	@echo "DEB package built. Check ../hush-relay_*.deb"

# --- RPM packaging ---
rpm: dist
	rpmbuild -bb hush-relay.spec
	@echo
	@echo "RPM package built. Check ~/rpmbuild/RPMS/*/hush-relay-*.rpm"

# --- Flatpak packaging ---
flatpak:
	flatpak-builder --force-clean build-dir io.github.coldcanuk.hush.yml
	@echo
	@echo "Flatpak built. Install with:"
	@echo "  flatpak-builder --force-clean --install-deps-from=flathub build-dir io.github.coldcanuk.hush.yml"

# --- OpenBSD packaging (pkg_add / pkg_create) ---
openbsd:
	sh scripts/package-openbsd.sh
	@echo
	@echo "OpenBSD stage complete. See dist/openbsd/ and openbsd/README.md"

# --- FreeBSD packaging (pkg / pkg create) ---
freebsd:
	sh scripts/package-freebsd.sh
	@echo
	@echo "FreeBSD stage complete. See dist/freebsd/ and freebsd/README.md"

# --- Both BSD families ---
bsd: openbsd freebsd

# --- Source tarball ---
dist:
	git archive --prefix=hush-$(shell cat VERSION)/ -o hush-$(shell cat VERSION).tar.gz HEAD
	@echo
	@echo "Source tarball created: hush-$(shell cat VERSION).tar.gz"

# Legacy aliases (keep for backward compat)
package-deb: deb
package-rpm: rpm
packages: deb rpm openbsd freebsd
