# Top-level Makefile for Hush C (Linux + *BSD)
# Workflow:
#   ./configure [PREFIX=...]
#   make
#   make test
#   make install [PREFIX=...]     # installs hush-relay + .desktop + icons
#   make uninstall                # removes PREFIX artifacts install owns (keeps build tree)
#   make clean                    # uninstalls PREFIX artifacts, then scrubs the
#                                 # build tree (objects, libs, in-tree binary,
#                                 # tarballs), so the next
#                                 # ./configure ; make ; make install starts
#                                 # from a clean install. Never touches
#                                 # ~/.hush/ runtime data.
#   make deb                      # Build DEB package (requires debhelper)
#   make rpm                      # Build RPM package (requires rpmbuild)
#   make flatpak                  # Build Flatpak package (requires flatpak-builder)
#   make openbsd                  # Stage OpenBSD destroot; pkg_create on OpenBSD
#   make freebsd                  # Stage FreeBSD destroot; pkg create on FreeBSD
#   make bsd                      # openbsd + freebsd
#   make dist                     # Create source tarball

# config.mk is generated by ./configure; the ?= defaults below let
# `make clean` / `make uninstall` run safely even when it is absent
# (virgin checkout), resolving to the same PREFIX=~/.local default.
-include config.mk

PREFIX ?= $(HOME)/.local
BINDIR ?= $(PREFIX)/bin
DATADIR ?= $(PREFIX)/share
# Rebuild guard port: $HUSH_PORT, else 10555 (HUSH_DEFAULT_PORT).
# Override per-invocation, e.g. `HUSH_PORT=10556 make`.
GUARD_PORT ?= $(HUSH_PORT)

.PHONY: all test clean install uninstall guard check-prefix package-deb package-rpm packages deb rpm flatpak openbsd freebsd bsd dist
# guard: is defined below but must never become the default goal.
.DEFAULT_GOAL := all

# Fail-loud when a live relay owns the guard port: never build or install
# over a running hive. Stop it first (`hush-relay --quit <port>`); `make
# clean` (kill-relay.sh) is the only path that kills.
guard:
	@sh scripts/check-relay-port.sh $(GUARD_PORT)

# An empty PREFIX would resolve BINDIR to /bin and let install/uninstall
# scribble outside any prefix. configure refuses to generate one; this
# catches `make install PREFIX=` style overrides instead.
check-prefix:
	@if [ -z "$(PREFIX)" ]; then \
		echo "error: empty PREFIX. Pass a real prefix, e.g. make install PREFIX=/tmp/hush-eval,"; \
		echo "or unset PREFIX to use the configured default (\$$HOME/.local)."; \
		exit 1; \
	fi

all: guard
	$(MAKE) -C hush-c all CC="$(CC)" CFLAGS="$(CFLAGS)" LDFLAGS="$(LDFLAGS)"

test:
	$(MAKE) -C hush-c test CC="$(CC)" CFLAGS="$(CFLAGS)" LDFLAGS="$(LDFLAGS)"

clean: check-prefix
	@sh scripts/kill-relay.sh
	$(MAKE) -C hush-c clean
	$(MAKE) uninstall
	rm -f *.tar.gz

install: guard check-prefix
	$(MAKE) -C hush-c install \
		DESTDIR="$(DESTDIR)" \
		PREFIX="$(PREFIX)" \
		BINDIR="$(BINDIR)" \
		DATADIR="$(DATADIR)" \
		ENABLE_STUN_TURN="$(ENABLE_STUN_TURN)"
	@echo
	@echo "To refresh your application launcher (Linux):"
	@echo "  update-desktop-database $(DATADIR)/applications || true"
	@echo "  gtk-update-icon-cache -f $(DATADIR)/icons/hicolor || true"
	@echo
	@echo "hush-relay should now appear in your menu / launcher."

uninstall: check-prefix
	$(MAKE) -C hush-c uninstall \
		DESTDIR="$(DESTDIR)" \
		PREFIX="$(PREFIX)" \
		BINDIR="$(BINDIR)" \
		DATADIR="$(DATADIR)"

# --- DEB packaging ---
deb:
	dpkg-buildpackage -us -uc -b
	@echo
	@echo "DEB package built. Check ../hush-relay_*.deb"

# --- RPM packaging ---
rpm: dist
	rpmbuild -bb hush-relay.spec
	@echo
	@echo "RPM package built. Check ~/rpmbuild/RPMS/*/hush-relay-*.rpm"

# --- Flatpak packaging ---
flatpak:
	flatpak-builder --force-clean build-dir io.github.coldcanuk.hush.yml
	@echo
	@echo "Flatpak built. Install with:"
	@echo "  flatpak-builder --force-clean --install-deps-from=flathub build-dir io.github.coldcanuk.hush.yml"

# --- OpenBSD packaging (pkg_add / pkg_create) ---
openbsd:
	sh scripts/package-openbsd.sh
	@echo
	@echo "OpenBSD stage complete. See dist/openbsd/ and openbsd/README.md"

# --- FreeBSD packaging (pkg / pkg create) ---
freebsd:
	sh scripts/package-freebsd.sh
	@echo
	@echo "FreeBSD stage complete. See dist/freebsd/ and freebsd/README.md"

# --- Both BSD families ---
bsd: openbsd freebsd

# --- Source tarball ---
dist:
	git archive --prefix=hush-$(shell cat VERSION)/ -o hush-$(shell cat VERSION).tar.gz HEAD
	@echo
	@echo "Source tarball created: hush-$(shell cat VERSION).tar.gz"

# Legacy aliases (keep for backward compat)
package-deb: deb
package-rpm: rpm
packages: deb rpm openbsd freebsd
