const assert = require('node:assert/strict');
const {spawn} = require('node:child_process');
const {once} = require('node:events');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const readline = require('node:readline');
// Browser dependencies are supplied explicitly; this test installs nothing.
const {chromium} = require(process.env.HUSH_PLAYWRIGHT_MODULE || 'playwright');
const artifacts = process.env.HUSH_TEST_UI_ARTIFACTS || fs.mkdtempSync(path.join(os.tmpdir(), 'hush-ui-proof-'));
fs.mkdirSync(artifacts, {recursive:true});
(async () => {
 const fixture = spawn('python3', [path.join(__dirname, 'check_collaboration.py'), '--serve-ui'], {stdio:['pipe','pipe','inherit']});
 const exited = once(fixture, 'exit');
 const lines = readline.createInterface({input:fixture.stdout});
 let browser;
 try {
 const first = await Promise.race([once(lines, 'line'), exited.then(()=>{throw new Error('UI fixture exited before startup');})]);
 const base = JSON.parse(first[0]).url;
 browser = await chromium.launch({executablePath:process.env.HUSH_BROWSER_EXECUTABLE,headless:true,args:['--no-sandbox']});
 const page=await browser.newPage({viewport:{width:1440,height:1000}});
 const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('Browser error:',e.message);});page.setDefaultTimeout(10000);
 const getSession=async()=>(await page.request.get(base + '/api/session')).json();
 await page.goto(base);await page.waitForSelector('#hive.show');
 await page.locator('#nav-new-channel').click();await page.locator('#new-chan').fill('Design review');
 await page.locator('#new-chan-prompt').fill('🌿'.repeat(501));
 await page.locator('#new-chan-save').click();assert.equal((await getSession()).channels.some(c=>c.slug==='design-review'),false);
 await page.locator('#new-chan-prompt').fill('🌿'.repeat(500));
 await page.locator('#new-chan-save').click();await page.locator('#new-chan-drawer').waitFor({state:'hidden'});
 assert.equal(Array.from((await getSession()).channels.find(c=>c.slug==='design-review').system_prompt).length,500);
 await page.getByRole('button',{name:'Options for #design-review',exact:true}).click();
 await page.locator('#chan-menu button[data-act="manage"]').click();
 await page.locator('#manage-prompt').fill('Help us finish the design.');await page.locator('#manage-save').click();
 await page.locator('#manage-chan').waitFor({state:'hidden'});
 assert.equal((await getSession()).channels.find(c=>c.slug==='design-review').system_prompt,'Help us finish the design.');
 console.log('Room create/manage, 500 Unicode boundary and 501 rejection OK');
 await page.locator('#inv-raise').click();await page.locator('#agent-name').fill('Morgan');
 await page.locator('#agent-prompt').fill('Help produce clear, practical design reviews.');
 for (const selected of await page.locator('.agent-provider-cb:checked').all()) await selected.uncheck();await page.locator('.agent-provider-cb[value="custom"]').check();
 await page.locator('.agent-provider-cb[value="openai-api"]').check();
 await page.getByRole('button',{name:'Move OpenAI API up',exact:true}).click();
 await page.getByRole('button',{name:'Configure Custom endpoint',exact:true}).click();
 await page.waitForSelector('#provider-drawer.show');
 assert.match(await page.locator('#provider-title').textContent(),/Custom endpoint/);await page.locator('#provider-close').click();
 await page.getByRole('button',{name:'Move OpenAI API down',exact:true}).click();
 await page.locator('#agent-pic-picker button').first().click();
 await page.locator('#agent-pass').uncheck();
 const skill=page.locator('#skill-armory button').first();const skillId=await skill.getAttribute('data-id');await skill.click();
 await page.locator('#agent-save').click();await page.locator('#agent-drawer').waitFor({state:'hidden'});
 let bot=(await getSession()).agents.find(a=>a.name==='Morgan');assert.ok(bot.skills.includes(skillId));assert.deepEqual(bot.providers,['custom','openai-api']);assert.ok(bot.picture);
 await page.getByRole('button',{name:'Edit Morgan',exact:true}).click();
 await page.locator('#skill-loadout button[data-id="'+skillId+'"]').click();await page.locator('#agent-save').click();
 await page.locator('#agent-drawer').waitFor({state:'hidden'});bot=(await getSession()).agents.find(a=>a.name==='Morgan');assert.equal(bot.skills.includes(skillId),false);
 console.log('Robot create, provider selection/reordering/configuration, skill assign/remove/save OK');
 await page.getByRole('button',{name:'#design-review',exact:true}).click();
 await page.getByRole('button',{name:'Chat with Morgan',exact:true}).click();
 await page.locator('#msg').fill('@Morgan Review this plan.');await page.locator('#send').click();
 await page.waitForFunction(()=>document.querySelector('#stream').textContent.includes('Thread · 2'));
 await page.getByRole('button',{name:'Chat with Morgan',exact:true}).click();await page.waitForSelector('#thread-pane.show');
 await page.waitForFunction(()=>document.querySelector('#thread-stream').textContent.includes('API_REPLY_ui_fixture'));
 assert.match(await page.locator('#thread-help').textContent(),/#design-review.*Started by/);
 await page.getByRole('button',{name:'#general',exact:true}).click();
 assert.ok((await page.locator('#thread-stream').textContent()).includes('API_REPLY_ui_fixture'));
 await page.locator('#thread-msg').fill('Keep this follow-up in its original room.');
 const request=page.waitForRequest(r=>r.url().endsWith('/api/event')&&r.method()==='POST');await page.locator('#thread-send').click();assert.equal((await request).postDataJSON().channel,'design-review');
 await page.waitForFunction(()=>!document.querySelector('#thread-send').disabled);
 await page.route('**/api/event',route=>route.fulfill({status:503,body:'deliberate test failure'}));
 await page.locator('#thread-msg').fill('Retain this thread draft.');await page.locator('#thread-send').click();
 await page.waitForFunction(()=>document.querySelector('#thread-send-error').textContent.includes('not sent'));
 assert.equal(await page.locator('#thread-msg').inputValue(),'Retain this thread draft.');await page.locator('#thread-close').click();
 await page.locator('#msg').fill('Retain this room draft.');await page.locator('#send').click();
 await page.waitForFunction(()=>document.querySelector('#send-error').textContent.includes('not sent'));assert.equal(await page.locator('#msg').inputValue(),'Retain this room draft.');await page.unroute('**/api/event');
 console.log('1:1 follow-up, original room routing and both failed-send drafts OK');
 await page.locator('#msg').fill('Ready to turn the project brief into practical next steps.');
 await page.locator('#send').click();await page.waitForFunction(()=>!document.querySelector('#msg').value);
 assert.equal((await page.locator('#stream').textContent()).includes('\"about\":'),false);
 await page.screenshot({path:path.join(artifacts,'workspace-desktop.png'),fullPage:true});
 await page.getByRole('button',{name:'Edit Morgan',exact:true}).click();await page.locator('#skill-loadout').scrollIntoViewIfNeeded();
 await page.screenshot({path:path.join(artifacts,'skills-desktop.png'),fullPage:true});await page.locator('#agent-close').click();
 await page.locator('#inv-seed').click();
 await page.locator('#seed-actions').fill('Research, Writing');
 await page.locator('#seed-project').fill('Prepare a practical project brief.');
 await page.locator('#seed-provider').selectOption('custom');
 await page.locator('#seed-channel-new').check();await page.locator('#seed-channel-name').fill('Project team');
 await page.locator('#seed-submit').click();await page.locator('#seed-drawer').waitFor({state:'hidden'});
 const team = (await getSession()).channels.find(c=>c.slug==='project-team');
 assert.equal(team.robots.length,2);assert.ok(team.system_prompt.includes('Prepare a practical project brief.'));
 assert.ok((await getSession()).agents.filter(a=>team.robots.includes(a.slug)).every(a=>a.provider==='custom'));
 console.log('Team creation, actual provider choice, room assignment and room guidance OK');
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(artifacts,'workspace-phone.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.ok(await page.locator('#msg').isVisible());
 assert.ok((await page.locator('#send').boundingBox()).y < 844);await page.locator('#nav-toggle').click();
 await page.getByRole('button',{name:'Edit Morgan',exact:true}).click();await page.locator('#skill-loadout').scrollIntoViewIfNeeded();
 await page.screenshot({path:path.join(artifacts,'skills-phone.png'),fullPage:true});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(errors,[]);
 console.log('Desktop/phone layouts and JavaScript errors OK');
 console.log('UI evidence:',artifacts);
 } finally {
   if (browser) await browser.close();
   fixture.stdin.end();
   await exited;
   lines.close();
 }
})().catch(e=>{console.error(e);process.exit(1)});
